# Generated by Django 3.1.1 on 2020-09-18 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={'verbose_name_plural': 'Paises'},
        ),
        migrations.AlterField(
            model_name='persona',
            name='tipo_documento',
            field=models.PositiveSmallIntegerField(choices=[(0, 'DNI'), (1, 'PASAPORTE'), (2, 'LIBRETA')]),
        ),
    ]
