# Generated by Django 3.1.1 on 2020-09-30 23:50

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_persona_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='puntos',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='coeficiente',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=3),
        ),
    ]
