# Generated by Django 3.1.2 on 2020-11-09 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200930_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='encargado',
            name='clave',
            field=models.CharField(default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='pais',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
