# Generated by Django 3.1.1 on 2020-11-30 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201109_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendedor',
            name='estoyHabilitado',
            field=models.BooleanField(default=True),
        ),
    ]
