# Generated by Django 3.1.1 on 2020-12-03 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_encargado_bajaencargado'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bajaCliente',
            field=models.BooleanField(default=False),
        ),
    ]
