# Generated by Django 4.2.2 on 2023-06-28 23:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cliente_bajacliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provincia',
            name='nombre',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
