# Generated by Django 4.2.1 on 2025-01-02 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_categoria_nombre_alter_servicio_nombre_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='persona',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/perfiles/'),
        ),
    ]
