# Generated by Django 4.2.1 on 2025-01-02 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_persona_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='persona',
            name='imagen',
        ),
        migrations.AddField(
            model_name='vendedor',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/perfiles/'),
        ),
    ]
