# Generated by Django 4.2.1 on 2025-05-07 00:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField()),
                ('baja', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=800)),
                ('email', models.EmailField(max_length=200)),
                ('telefono', models.CharField(max_length=200)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='media/hoteles/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
                ('encargado', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.encargado')),
                ('localidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.localidad')),
                ('servicios', models.ManyToManyField(to='core.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='TemporadaAlta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('inicio', models.DateField(verbose_name='fecha inicio')),
                ('fin', models.DateField(verbose_name='fecha fin')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporadas', to='hotel.hotel')),
            ],
        ),
        migrations.CreateModel(
            name='PrecioPorTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baja', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('alta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifario', to='hotel.hotel')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoteles', to='core.tipohabitacion')),
            ],
        ),
        migrations.CreateModel(
            name='PaqueteTuristico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('coeficiente', models.DecimalField(decimal_places=2, max_digits=3)),
                ('inicio', models.DateField()),
                ('fin', models.DateField()),
                ('vendido', models.BooleanField(default=False)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('habitaciones', models.ManyToManyField(related_name='paqueteturistico', to='hotel.habitacion')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquetesTuristicos', to='hotel.hotel')),
            ],
        ),
        migrations.AddField(
            model_name='hotel',
            name='tipos',
            field=models.ManyToManyField(through='hotel.PrecioPorTipo', to='core.tipohabitacion'),
        ),
        migrations.AddField(
            model_name='hotel',
            name='vendedores',
            field=models.ManyToManyField(to='core.vendedor'),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habitaciones', to='hotel.hotel'),
        ),
        migrations.AddField(
            model_name='habitacion',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.tipohabitacion'),
        ),
        migrations.CreateModel(
            name='Descuento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_habitaciones', models.PositiveSmallIntegerField()),
                ('coeficiente', models.DecimalField(decimal_places=2, max_digits=3)),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos', to='hotel.hotel')),
            ],
            options={
                'ordering': ['cantidad_habitaciones'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='habitacion',
            unique_together={('hotel', 'numero')},
        ),
    ]
