# Generated by Django 3.1.1 on 2020-09-30 23:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200930_2350'),
        ('hotel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='descuento',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='descuentos', to='hotel.hotel'),
        ),
        migrations.AlterField(
            model_name='precioportipo',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tarifario', to='hotel.hotel'),
        ),
        migrations.AlterField(
            model_name='precioportipo',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hoteles', to='core.tipohabitacion'),
        ),
        migrations.AlterField(
            model_name='temporadaalta',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temporadas', to='hotel.hotel'),
        ),
        migrations.AlterUniqueTogether(
            name='habitacion',
            unique_together={('hotel', 'numero')},
        ),
    ]
