# Generated by Django 3.1.2 on 2020-10-21 03:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_auto_20201003_1114'),
        ('hotel', '0002_auto_20200930_2350'),
    ]

    operations = [
    ]
