# Generated by Django 3.1.2 on 2020-11-09 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0003_merge_20201021_0007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='descuento',
            options={'ordering': ['cantidad_habitaciones']},
        ),
    ]
