# Generated by Django 3.1.2 on 2020-11-12 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201109_2024'),
        ('hotel', '0004_auto_20201109_2024'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='encargado',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.encargado'),
        ),
    ]
