# Generated by Django 3.1.2 on 2020-11-15 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0005_hotel_encargado'),
    ]

    operations = [
        migrations.AddField(
            model_name='habitacion',
            name='baja',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paqueteturistico',
            name='vendido',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hotel',
            name='email',
            field=models.EmailField(max_length=200),
        ),
    ]
