# Generated by Django 3.1.1 on 2020-11-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_auto_20201115_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='paqueteturistico',
            name='precio',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
