# Generated by Django 3.1.2 on 2020-11-19 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0007_paqueteturistico_precio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='precioportipo',
            name='alta',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='precioportipo',
            name='baja',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
