# Generated by Django 3.1.2 on 2020-11-21 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0010_auto_20201119_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='temporadaalta',
            name='fin',
            field=models.DateField(verbose_name='fecha fin'),
        ),
        migrations.AlterField(
            model_name='temporadaalta',
            name='inicio',
            field=models.DateField(verbose_name='fecha inicio'),
        ),
    ]
