# Generated by Django 3.1.2 on 2020-12-06 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0011_auto_20201121_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paqueteturistico',
            name='habitaciones',
            field=models.ManyToManyField(related_name='paquetesTuristicos', to='hotel.Habitacion'),
        ),
        migrations.AlterField(
            model_name='paqueteturistico',
            name='hotel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paquetesTuristicos', to='hotel.hotel'),
        ),
    ]
