# Generated by Django 3.1.2 on 2020-12-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_auto_20201206_1023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paqueteturistico',
            name='habitaciones',
            field=models.ManyToManyField(related_name='paqueteturistico', to='hotel.Habitacion'),
        ),
    ]
