# Generated by Django 4.2.1 on 2025-01-02 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0013_auto_20201206_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='media/hoteles/'),
        ),
    ]
