# Generated by Django 3.1.1 on 2020-11-16 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0006_auto_20201115_2031'),
        ('venta', '0002_auto_20200930_2350'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='paquete',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alquiler', to='hotel.paqueteturistico'),
        ),
    ]
