# Generated by Django 3.1.2 on 2020-12-06 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0012_auto_20201206_1023'),
        ('venta', '0003_auto_20201116_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alquiler',
            name='habitaciones',
            field=models.ManyToManyField(related_name='alquileres', to='hotel.Habitacion'),
        ),
    ]
